### ISSUE TITLE
Docker Container restarting as soon as it initialises

### ISSUE THREAD

**Issue by Hazy-Dayz** [brandongallagher1999/1337x-Bot#93]
```
1337x-bot-master-bot-1  | Entrypoint has been called...

1337x-bot-master-bot-1  | Starting Bot Container!

1337x-bot-master-bot-1  | /index.ts:17

1337x-bot-master-bot-1  |   token = JSON.parse(fs.readFileSync("./config.json").toString()).token;

1337x-bot-master-bot-1  |                ^

1337x-bot-master-bot-1  | SyntaxError: Unexpected token ' in JSON at position 2

1337x-bot-master-bot-1  |     at JSON.parse (<anonymous>)

1337x-bot-master-bot-1  |     at Object.<anonymous> (/index.ts:17:16)

1337x-bot-master-bot-1  |     at Module._compile (node:internal/modules/cjs/loader:1097:14)

1337x-bot-master-bot-1  |     at Module.m._compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:1371:23)

1337x-bot-master-bot-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

1337x-bot-master-bot-1  |     at Object.require.extensions.<computed> [as .ts] (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:1374:12)

1337x-bot-master-bot-1  |     at Module.load (node:internal/modules/cjs/loader:975:32)

1337x-bot-master-bot-1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

1337x-bot-master-bot-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

1337x-bot-master-bot-1  |     at main (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/bin.ts:331:12)

1337x-bot-master-bot-1  |     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/bin.ts:482:3)

1337x-bot-master-bot-1  |     at Module._compile (node:internal/modules/cjs/loader:1097:14)

1337x-bot-master-bot-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

1337x-bot-master-bot-1  |     at Module.load (node:internal/modules/cjs/loader:975:32)

1337x-bot-master-bot-1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

1337x-bot-master-bot-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

1337x-bot-master-bot-1  |     at node:internal/main/run_main_module:17:47

1337x-bot-master-bot-1 exited with code 1
```

**Comment by brandongallagher1999** [comment]
Did you create your token file?
```
TOKEN="your token goes in this string"

echo { '"token"' : '"'$TOKEN'"' } > config.json
```

**Comment by Hazy-Dayz** [comment]
> Did you create your token file?
> 
> ```
> TOKEN="your token goes in this string"
> 
> echo { '"token"' : '"'$TOKEN'"' } > config.json
> ```

I am not certain how on windows, it doesnt explain too well

**Comment by brandongallagher1999** [comment]
Ah, then you need to enable WSL and use the Linux terminal to set environment variables.

https://www.windowscentral.com/install-windows-subsystem-linux-windows-10

**Comment by Hazy-Dayz** [comment]
ah, ok will have a look soon
